name: BuildApp

# Controls when the workflow will run
on:
  push:
    branches: 
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  install:
    strategy:
      matrix:
        go_version:
          - '1.17'
          - '1.18'
          - '>=1.18'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build Database
        run: docker-compose build

      - name: Create Database
        run: docker-compose up -d

  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Test App
        run: go test -v main_test.go
  
  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build App
        run: go build -v main.go

